app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
    path('cal/', include("cal.urls")),
    path('users/', include("users.urls")),

]

app/cal/urls.py
from django.urls import path

from . import views

#pip install django-mathfilters

app_name = "cal"

urlpatterns = [
    path("", views.index, name="index"),
    path("week", views.weekview, name="weekview"),
    path("month", views.monthviewer, name="monthview"),
    path("month/<int:month_date>/<int:day_date>/<int:year_date>", views.monthviewer, name="monthviewer"),
    path("week/<int:month_date>/<int:day_date>/<int:year_date>", views.weekview, name="weekviewer"),
    path("week/<int:month_date>/<int:day_date>/<int:year_date>/event/<int:event_id>", views.eventweekcard, name="weekeventcard"),
    path("month/<int:month_date>/<int:day_date>/<int:year_date>/<int:selected_day>", views.monthevent, name="monthevent"),
    path("month/<int:month_date>/<int:day_date>/<int:year_date>/event/<int:event_id>", views.eventmonthcard, name="montheventcard"),
    path("agenda", views.agendaview, name="agendaview"),
    path("month/create", views.create_event_card, name="montheventcreate"),
    path("week/create", views.create_event_card, name="weekeventcreate"),
    path("month/<int:month_date>/<int:day_date>/<int:year_date>/<int:selected_day>/create", views.create_event_card, name="dayeventcreate"),
    path("month/<int:month_date>/<int:day_date>/<int:year_date>/event/<int:event_id>/edita/<int:selected_day>", views.modifyattendees, name="montheditattendees"),
    path("month/<int:month_date>/<int:day_date>/<int:year_date>/event/<int:event_id>/edit/<int:selected_day>", views.editevent, name="montheventedit")
]

app/users/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "users"

# Added urls for all the user related pages
urlpatterns = [
    path("", views.index, name="user_landing"),
    path('login/', views.login_page, name = 'login_page'),
    path('register/', views.register_page, name = 'register_page'),
    path('username_get/', views.username_get_page, name = 'username_get_page'),
    path('password_reset/', views.password_reset_page, name = "password_reset"),
    path('password_change/', views.password_change_page, name = 'password_change_page'),
    path('password_confirm/', views.password_confirm_page, name = 'password_confirm_page'),
    path('account_information/', views.account_information_page, name = 'account_information_page'),
    path('friend_list/', views.friend_list_page, name = 'friend_list_page'),
    path('accept_friend/<friend_username>/', views.accept_friend, name='accept_friend'),
    path('reject_friend/<friend_username>/', views.reject_friend, name='reject_friend'),
    path('update_friend/<friend_username>/', views.update_friend, name='update_friend'),
]

app/cal/forms.py
from django import forms
from .models import Event
from django.utils import timezone
from django.views.generic.edit import UpdateView

from users.models import Profile

# manages event creation and validation
class EventForm(forms.ModelForm):
    # fields for varying info per event object
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))

    class Meta:
        model = Event 
        fields = ['title', 'start_date', 'start_time', 'end_date', 'end_time', 'description', 'location']
        template_name = "calendar/month_event_format.html"

    # performs custom validation and data processing
    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        start_time = cleaned_data.get("start_time")
        end_date = cleaned_data.get("end_date")
        end_time = cleaned_data.get("end_time")

        #combine to single object + make timezone aware
        if start_date and start_time:
            cleaned_data['start_time'] = timezone.make_aware(
                timezone.datetime.combine(start_date, start_time)
            )
        if end_date and end_time:
            cleaned_data['end_time'] = timezone.make_aware(
                timezone.datetime.combine(end_date, end_time)
            )

        # validate that end time is after start time
        if cleaned_data.get("start_time") and cleaned_data.get("end_time"):
            if cleaned_data["end_time"] <= cleaned_data["start_time"]:
                self.add_error("end_time", "End time must be after start time.")
        return cleaned_data

# form to make each user an attendee per event
class AttendeeForm(forms.ModelForm):
    attendee = forms.ModelMultipleChoiceField(
        queryset=Profile.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Attendees"
    )
    
    class Meta:
        model = Event
        fields = ['attendee']

    def __init__(self, *args, **kwargs):
        # Extract the current user from the kwargs
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        # Filter the queryset to exclude the current user
        if user:
            self.fields['attendee'].queryset = Profile.objects.exclude(user=user)
        else:
            self.fields['attendee'].queryset = Profile.objects.all()

# form to edit the event form through different methods of validation
class EditEventForm(forms.ModelForm):

    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))

    class Meta:
        model = Event
        fields = ['title', 'start_date', 'start_time', 'end_date', 'end_time', 'description', 'location']

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        start_time = cleaned_data.get("start_time")
        end_date = cleaned_data.get("end_date")
        end_time = cleaned_data.get("end_time")

        # Combine date and time for start and end times while preserving original dates
        if start_date and start_time:
            cleaned_data['start_datetime'] = timezone.make_aware(
                timezone.datetime.combine(start_date, start_time)
            )
        if end_date and end_time:
            cleaned_data['end_datetime'] = timezone.make_aware(
                timezone.datetime.combine(end_date, end_time)
            )

        # Validate that end time is after start time
        if cleaned_data.get("start_datetime") and cleaned_data.get("end_datetime"):
            if cleaned_data["end_datetime"] <= cleaned_data["start_datetime"]:
                self.add_error("end_time", "End time must be after start time.")

        return cleaned_data

app/cal/views.py
from django.http import HttpResponse, Http404
from django.template import loader

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event
from .forms import EventForm, AttendeeForm, EditEventForm
from .models import User, Notifications 
from .utilities import save_user
from django.utils import timezone
from .forms import EventForm
from django.http import JsonResponse
from django.views.generic.edit import UpdateView
from .models import Event
from .date_get import getOffset, getNextOffset, get_week_range, getNextMonth, getNextMonthName, getNextOffsetDate, getPreviousMonth, getPreviousMonthName

import datetime
import calendar
import json


from .models import User

#we will need a view start to determine when to render calendar
  
def getPrevMonth():
  today = datetime.datetime.today()
  first = today.replace(day=1)
  last_month = first - datetime.timedelta(days=1)
  return last_month

def getPrevMonthName():
  today = datetime.datetime.today()
  first = today.replace(day=1)
  last_month = first - datetime.timedelta(days=1)
  return last_month.strftime("%B")
  


@login_required(login_url='/users/login')
def index(request):
  
  current_month_name = datetime.datetime.today().strftime("%B")

  prev_month_value = 1
  prev_day_value = 1
  prev_year_value = 2024

  context = {
    "current_month" : current_month_name,
    "prev_month_value" : prev_month_value,
    "prev_day_value" : prev_day_value,
    "prev_year_value" : prev_year_value,

  }
  return render(request, "calendar/base.html", context)

@login_required(login_url='/users/login')
def weekview(request, month_date=int(datetime.datetime.now().strftime('%m')), 
               day_date=int(datetime.datetime.now().strftime('%d')), 
               year_date=int(datetime.datetime.now().strftime('%Y'))):

  hour_num = list(range(0, 24))
  day_names = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"]
  specific_date = datetime.datetime(year_date, month_date, day_date)
  start_of_week = specific_date - datetime.timedelta(days=(specific_date.weekday() + 1) % 7)
  end_of_week = start_of_week + datetime.timedelta(days=7)
  start_month_value = start_of_week.strftime('%m')
  start_day_value = start_of_week.strftime('%d')
  start_year_value = start_of_week.strftime('%Y')

  first_date = get_week_range(specific_date)
  current_month_name = datetime.datetime.today().strftime("%B") 


  #Checks if it is the current date
  now = datetime.datetime.now()
  current_month_value = now.strftime('%m')
  current_day_value = now.strftime('%d')
  current_year_value = now.strftime('%Y')
  current_day_name = datetime.datetime.today().strftime("%A")
  days = [int((start_of_week + datetime.timedelta(days=i)).strftime('%d')) for i in range(7)]

  next_week_start = start_of_week + datetime.timedelta(days=7)
  next_week_day = next_week_start.strftime('%d')
  next_week_month = next_week_start.strftime('%m')
  next_week_year = next_week_start.strftime('%Y')

  prev_week_end = start_of_week - datetime.timedelta(days=1)
  prev_week_date = prev_week_end.strftime('%d')
  prev_week_month = prev_week_end.strftime('%m')
  prev_week_year = prev_week_end.strftime('%Y')


  #Mini Calendar
  #Get current date
  now = datetime.datetime.now()
  first_day_of_month = now.replace(day=1)
  weekday_name = first_day_of_month.strftime('%A')
  current_month_value = int(now.strftime('%m'))
  current_day_value = int(now.strftime('%d'))
  current_year_value = int(now.strftime('%Y'))
  current_month_days = calendar.monthrange(current_year_value, current_month_value)[1]
  month_days = list(range(1, current_month_days + 1))
  start_date = datetime.date(current_year_value, current_month_value, current_day_value)
  prev_month = getPreviousMonth(start_date)
  prev_date = calendar.monthrange(prev_month.year, prev_month.month)[1]
  prev_month_value = prev_month.strftime('%m')
  next_month = getNextMonth(start_date, current_month_days)
  next_month_value = next_month.strftime('%m')
  offset = getOffset(weekday_name)
  last_day = start_date.replace(day=current_month_days)
  offset_nums = list(range( prev_date - int(offset) + 1, prev_date + 1))
  next_offset = getNextOffsetDate(last_day.strftime('%A'))
  next_offset_nums = list(range(1, next_offset + 1 ))
  #end of mini calendar

  if int(start_month_value) == current_month_value:
     today_is_true = True
  else:
     today_is_true = False

  #gets current logged in user
  current_user = request.user
  current_user_events = current_user.profile.created_events.all()
  attending_events = current_user.profile.events.all()
  current_user_events = (current_user_events | attending_events).distinct()
  todays_events = current_user_events.filter(start_time__month=month_date, start_time__day=day_date)
  month_events = current_user_events.filter(start_time__month=month_date, start_time__year=year_date)
  next_month_events = current_user_events.filter(start_time__month=next_month_value, start_time__year=year_date)
  prev_month_events = current_user_events.filter(start_time__month=prev_month_value, start_time__year=year_date)
  
  week_events = current_user_events.filter(start_time__lt=end_of_week, end_time__gte=start_of_week)

  context = {
    "start_of_week" : start_of_week,
    "end_of_week" : end_of_week,
    "current_month_value" : current_month_value,
    "current_day_value" : current_day_value,
    "current_year_value" : current_year_value,
    "day_names" : day_names,
    "day_nums" : days,
    "hours" : hour_num,
    "today_date" : timezone.now().day,
    "today_name"  : current_day_name,
    "first" : first_date,
    "current_month" : current_month_name,
    "next_week_day" : next_week_day,
    "next_week_month" : next_week_month,
    "next_week_year" : next_week_year,
    "prev_week_day" : prev_week_date,
    "prev_week_month" : prev_week_month,
    "prev_week_year" : prev_week_year,
    "prev_date" : prev_week_end.strftime('%d'),
    "start_month_value" : start_month_value,
    "start_day_value" : start_day_value,
    "start_year_value" : start_year_value,
    "events" : week_events,
    "current_user" : current_user,
    "today_is_true" : today_is_true,
    
    "month_days_list" : month_days,
    "day_offset" : offset,
    "month_events" : month_events,
    "next_month_events" : next_month_events,
    "prev_month_events" :prev_month_events,
    "next_offset" : next_offset,
    "next_offset_nums" : next_offset_nums,
    "current_days" : current_month_days,
  }

  return render(request, "calendar/weekviewer.html", context)

@login_required(login_url='/users/login')
def eventweekcard(request, month_date=int(datetime.datetime.now().strftime('%m')), 
               day_date=int(datetime.datetime.now().strftime('%d')), 
               year_date=int(datetime.datetime.now().strftime('%Y')), event_id = Event.objects.first()):

  hour_num = list(range(0, 24))
  day_names = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"]
  specific_date = datetime.datetime(year_date, month_date, day_date)
  start_of_week = specific_date - datetime.timedelta(days=(specific_date.weekday() + 1) % 7)
  end_of_week = start_of_week + datetime.timedelta(days=7)
  start_month_value = start_of_week.strftime('%m')
  start_day_value = start_of_week.strftime('%d')
  start_year_value = start_of_week.strftime('%Y')

  first_date = get_week_range(specific_date)
  current_month_name = datetime.datetime.today().strftime("%B") 


  #Checks if it is the current date
  now = datetime.datetime.now()
  current_month_value = now.strftime('%m')
  current_day_value = now.strftime('%d')
  current_year_value = now.strftime('%Y')
  current_day_name = datetime.datetime.today().strftime("%A")
  days = [int((start_of_week + datetime.timedelta(days=i)).strftime('%d')) for i in range(7)]

  next_week_start = start_of_week + datetime.timedelta(days=7)
  next_week_day = next_week_start.strftime('%d')
  next_week_month = next_week_start.strftime('%m')
  next_week_year = next_week_start.strftime('%Y')

  prev_week_end = start_of_week - datetime.timedelta(days=1)
  prev_week_date = prev_week_end.strftime('%d')
  prev_week_month = prev_week_end.strftime('%m')
  prev_week_year = prev_week_end.strftime('%Y')


  #Mini Calendar
  #Get current date
  now = datetime.datetime.now()
  first_day_of_month = now.replace(day=1)
  weekday_name = first_day_of_month.strftime('%A')
  current_month_value = int(now.strftime('%m'))
  current_day_value = int(now.strftime('%d'))
  current_year_value = int(now.strftime('%Y'))
  current_month_days = calendar.monthrange(current_year_value, current_month_value)[1]
  month_days = list(range(1, current_month_days + 1))
  start_date = datetime.date(current_year_value, current_month_value, current_day_value)
  prev_month = getPreviousMonth(start_date)
  prev_date = calendar.monthrange(prev_month.year, prev_month.month)[1]
  prev_month_value = prev_month.strftime('%m')
  next_month = getNextMonth(start_date, current_month_days)
  next_month_value = next_month.strftime('%m')
  offset = getOffset(weekday_name)
  last_day = start_date.replace(day=current_month_days)
  offset_nums = list(range( prev_date - int(offset) + 1, prev_date + 1))
  next_offset = getNextOffsetDate(last_day.strftime('%A'))
  next_offset_nums = list(range(1, next_offset + 1 ))
  #end of mini calendar

  if start_month_value == current_month_value:
    today_is_true = True
  else:
    today_is_true = False

  #gets current logged in user
  current_user = request.user
  current_user_events = current_user.profile.created_events.all()
  attending_events = current_user.profile.events.all()
  current_user_events = (current_user_events | attending_events).distinct()
  todays_events = current_user_events.filter(start_time__month=month_date, start_time__day=day_date)
  month_events = current_user_events.filter(start_time__month=month_date, start_time__year=year_date)

app/cal/templates/calendar/agendaview.html
{% extends "calendar/base.html" %}

{% block title %}
My Calendar
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/agendaview.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}
{% load calendar_filters %}


<div>
  {{ current_user }}
</div>

<div>
  {{ user_events }}
</div>


{% endblock %}

app/cal/templates/calendar/attendees_form.html
{% for field in form %}
  <div class="">


    <div class="">
      <div class="">
        {{ field.label_tag }}
      </div>
        {{ field }}
    </div>
    <div class="">
      {{ field.errors }}
    </div>

  </div>
  <div class="">

  </div>
{% endfor %}

app/cal/templates/calendar/editevent.html
{% extends "calendar/monthviewer.html" %}

{% block title %}
My Calendar
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/monthview.css' %}">
<link rel="stylesheet" href="{% static 'calendar/monthevent.css' %}">
<link rel="stylesheet" href="{% static 'calendar/month-event-form.css' %}">

{% endblock %}

{% block monthviewer_content %}

{% load mathfilters %}

<div class="month-event-container">
  <div class="outer-container">


    <div class="outer-info-container">
    </div>
    <div class="inner-container">
    <div class="event-form-edit">

      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="">  
            <div class="">
              <div class="">
                {{ field.label_tag }}
              </div>
                {{ field }}
            </div>
            <div class="">
              {{ field.errors }}
            </div>

          </div>
          <div class="">

          </div>
        {% endfor %}
  
        <button type="submit" class="edit-button">
          Edit Event
        </button>
      </form>

      
    </div>
    
    </div>
  </div>

</div>

{% endblock %}

app/cal/templates/calendar/eventcreatecard.html
{% extends "calendar/monthviewer.html" %}

{% block title %}
My Calendar
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/monthview.css' %}">
<link rel="stylesheet" href="{% static 'calendar/monthevent.css' %}">
<link rel="stylesheet" href="{% static 'calendar/month-event-form.css' %}">

{% endblock %}

{% block monthviewer_content %}

{% load mathfilters %}

<div class="month-event-container">
  <div class="outer-container">

    <div class="event-form">

      <form method="post">
        {% csrf_token %}
        {{ form }}
  
        <button type="submit">
          Create Event
        </button>
      </form>

      
    </div>
    

  </div>

</div>

{% endblock %}

app/cal/templates/calendar/eventmonthcard.html
{% extends "calendar/monthviewer.html" %}

{% block title %}
My Calendar
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/monthview.css' %}">
<link rel="stylesheet" href="{% static 'calendar/monthevent.css' %}">
<link rel="stylesheet" href="{% static 'calendar/eventcard.css' %}">

{% endblock %}

{% block monthviewer_content %}

{% load mathfilters %}

<div class="month-event-container">
  
  <div class="outer-container">
    <div class="outer-info-container">
      {% url 'cal:monthviewer' month_date=start_month_value day_date=start_day_value year_date=start_year_value as month_viewer %}
      <div class="exit-container">
        <a href ="{{ month_viewer }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="31" height="31" viewBox="0 0 31 31" fill="none">
          <circle cx="15.5" cy="15.5" r="15.5" fill="#DC2626"/>
          <circle cx="15.5" cy="15.5" r="15.5" fill="black" fill-opacity="0.2"/>
          <path d="M13.7358 12.0909L15.7386 15.9048L17.7912 12.0909H20.8949L17.7344 17.5455L20.9801 23H17.8906L15.7386 19.2287L13.6222 23H10.4972L13.7358 17.5455L10.6108 12.0909H13.7358Z" fill="white"/>
          </svg>
        </a>
      </div>
      <div class="outer-info">
        {{ start_date }}
        </div>

      {% url 'cal:montheventedit' month_date=start_month_value day_date=start_day_value year_date=start_year_value event_id=selected_event.id selected_day=selected_day as editevent %}
      <a href="{{ editevent }}">
      <div class="add-link-container">

        <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="35" height="35" viewBox="0 0 48 48" fill="#fff">
          <path d="M 36 5.0097656 C 34.205301 5.0097656 32.410791 5.6901377 31.050781 7.0507812 L 8.9160156 29.183594 C 8.4960384 29.603571 8.1884588 30.12585 8.0253906 30.699219 L 5.0585938 41.087891 A 1.50015 1.50015 0 0 0 6.9121094 42.941406 L 17.302734 39.974609 A 1.50015 1.50015 0 0 0 17.304688 39.972656 C 17.874212 39.808939 18.39521 39.50518 18.816406 39.083984 L 40.949219 16.949219 C 43.670344 14.228094 43.670344 9.7719064 40.949219 7.0507812 C 39.589209 5.6901377 37.794699 5.0097656 36 5.0097656 z M 36 7.9921875 C 37.020801 7.9921875 38.040182 8.3855186 38.826172 9.171875 A 1.50015 1.50015 0 0 0 38.828125 9.171875 C 40.403 10.74675 40.403 13.25325 38.828125 14.828125 L 36.888672 16.767578 L 31.232422 11.111328 L 33.171875 9.171875 C 33.957865 8.3855186 34.979199 7.9921875 36 7.9921875 z M 29.111328 13.232422 L 34.767578 18.888672 L 16.693359 36.962891 C 16.634729 37.021121 16.560472 37.065723 16.476562 37.089844 L 8.6835938 39.316406 L 10.910156 31.521484 A 1.50015 1.50015 0 0 0 10.910156 31.519531 C 10.933086 31.438901 10.975086 31.366709 11.037109 31.304688 L 29.111328 13.232422 z"></path>
          </svg>
        
      </div>
      </a>
    </div>
    <div class="inner-container">
      <div class="inner-info">
        <div class="header">
          
          <div class="title">
            {{ selected_event.title }}
          </div>
          <div class="location">
            {{ selected_event.location }}
          </div>
        </div>
        <div class="line">
        </div>

        <div class="body">

          <div class="start_time">
            {{ selected_event.start_time }}
          </div>
          <div class="end_time">
            {{ selected_event.end_time }}
          </div>
        </div>
      
        <div class="line">
        </div>

        <div class="description">

          {{ selected_event.description }}

        </div>
        <div class="line">
        </div> 
        
        {% block attendee %}

        {% endblock %}

      </div>


    </div>

  </div>

</div>







{% endblock %}

app/cal/templates/calendar/month_event_format.html
{% for field in form %}
  <div class="field-content">


    <div class="reg-creation">
      <div class="form-label">
        {{ field.label_tag }}
      </div>
        {{ field }}
    </div>
    <div class="field-error">
      {{ field.errors }}
    </div>

  </div>
  <div class="thin-line">

  </div>
{% endfor %}

app/cal/templates/calendar/monthevent.html
{% extends "calendar/monthviewer.html" %}

{% block title %}
My Calendar
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/monthview.css' %}">
<link rel="stylesheet" href="{% static 'calendar/monthevent.css' %}">

{% endblock %}

{% block monthviewer_content %}

{% load mathfilters %}

<div class="month-event-container">
  
  <div class="outer-container">
    <div class="outer-info-container">
      {% url 'cal:monthviewer' month_date=start_month_value day_date=start_day_value year_date=start_year_value as month_viewer %}
      <div class="exit-container">
        <a href ="{{ month_viewer }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="31" height="31" viewBox="0 0 31 31" fill="none">
          <circle cx="15.5" cy="15.5" r="15.5" fill="#DC2626"/>
          <circle cx="15.5" cy="15.5" r="15.5" fill="black" fill-opacity="0.2"/>
          <path d="M13.7358 12.0909L15.7386 15.9048L17.7912 12.0909H20.8949L17.7344 17.5455L20.9801 23H17.8906L15.7386 19.2287L13.6222 23H10.4972L13.7358 17.5455L10.6108 12.0909H13.7358Z" fill="white"/>
          </svg>
        </a>
      </div>
      <div class="outer-info">
        {{ start_date }}
      </div>
      <div class="add-link-container">
        
        {% url 'cal:dayeventcreate' month_date=start_month_value day_date=start_day_value year_date=start_year_value selected_day=selected_day as create_event %}
        <a href ='{{ create_event }}'>
          +
        </a>
      </div>
    </div>
    <div class="inner-container">
      <div class="inner-info">
        <div class="selected-day-event-container">
          {% for event in current_day_event %}

          {% url 'cal:montheventcard' month_date=start_month_value day_date=start_day_value year_date=start_year_value event_id=event.id as montheventcard %}
          <a href ="{{ montheventcard }}">
          <div class="events-container">
            <div class="selected-day-event">
              <div class="red-main-event-bar">
                
              </div>
              <div class="event-card">
                <div class="event-card-time">
                  {{ event.start_time|time:'h:i A' }}
                </div>
                <div class="event-card-title">
                  {{ event.title }}
                </div>
                <div class="event-card-location">
                  {{ event.location }}
                </div>
              </div>
            </div>

          </a>

          </div>

          {% endfor %}
        </div>
      </div>


    </div>

  </div>

</div>







{% endblock %}