app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("core.urls")),
    path('admin/', admin.site.urls),
    path('cal/', include("cal.urls")),
    path('users/', include("users.urls")),

]

app/users/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "users"

# Added urls for all the user related pages
urlpatterns = [
    path("", views.index, name="user_landing"),
    path('login/', views.login_page, name = 'login_page'),
    path('register/', views.register_page, name = 'register_page'),
    path('username_get/', views.username_get_page, name = 'username_get_page'),
    path('password_reset/', views.password_reset_page, name = "password_reset"),
    path('password_change/', views.password_change_page, name = 'password_change_page'),
    path('password_confirm/', views.password_confirm_page, name = 'password_confirm_page'),
    path('account_information/', views.account_information_page, name = 'account_information_page'),
    path('friend_list/', views.friend_list_page, name = 'friend_list_page'),
    path('accept_friend/<friend_username>/', views.accept_friend, name='accept_friend'),
    path('reject_friend/<friend_username>/', views.reject_friend, name='reject_friend'),
    path('update_friend/<friend_username>/', views.update_friend, name='update_friend'),
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Created a model that stored the user's friend inside 
class Friends(models.Model):
    Amigo = models.ForeignKey(User, on_delete=models.CASCADE)
    requestPending = models.BooleanField(default = True)
    viewable = models.BooleanField(default = True)

# Created a model that stores all of the user information, including their friends
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #notifications = models.ManyToManyField(Notifications, related_name='users', blank=True)
    friendList = models.ManyToManyField(Friends, related_name='users', blank=True)
    isViewer = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

app/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from .models import *
import random
from .models import Friends, Profile
from django.http import JsonResponse

from django.utils import timezone
import datetime
import calendar

from cal.date_get import getOffset, getNextOffset, get_week_range, getNextMonth, getNextMonthName, getNextOffsetDate, getPreviousMonth, getPreviousMonthName

RESET_PASSWORD_USERNAME = ""
NUMBER = ""
CURRENT_USER = None

# Create your views here.
def index(request):
    return render(request, 'home.html')

# Logs into the system with the designated username and password of the user
def login_page(request):
    global CURRENT_USER
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
    
        if not User.objects.filter(username = username).exists():
            messages.error(request, 'Invalid Username')
            return redirect('/users/login')
    
        user = authenticate(username = username, password = password)

        if user is None:
            messages.error(request, "Invalid Password")
            return redirect('/users/login')
        else:
            login(request, user)
            CURRENT_USER = user
            CURRENT_USER.profile.isViewer = False
            return redirect('/cal/month') #replace with entrance to calander
        
    return render(request, 'login.html')

# Takes the information that was given in the page and turns it into a new user
def register_page(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.filter(username = username)

        if user.exists():
            messages.info(request, "Username Invalid")
            return redirect('/users/register')
    
        user = User.objects.create_user(first_name = first_name, last_name = last_name, email = email, username = username, password = password)
        profile = Profile(user = user, isViewer = False)


        user.save()
        profile.save()

        messages.info(request, "Account Created")
        return redirect('/users/login')
    
    return render(request, 'register.html')

# Gets the username of the account they want to reset their password in
def username_get_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        
        user = User.objects.filter(username = username)

        if not user.exists():
            messages.info(request, "User does not exist")
            return redirect('/users/username_get')
        else:
            user = User.objects.get(username = username)
            global RESET_PASSWORD_USERNAME
            RESET_PASSWORD_USERNAME = username
            return redirect('/users/password_reset')
    return render(request, 'username_get.html')

# Asks the user to take the code they got from their email and put it in here
def password_reset_page(request):
    global NUMBER 
    if request.method == 'POST':
        inserted_Number = request.POST.get('number')

        if inserted_Number == NUMBER:
            return redirect('/users/password_change')
        else:
            messages.error(request, "Not the correct number, new email is being sent")
            return redirect('/users/password_reset')

    # Sets up the code and sends the email
    NUMBER = ""
        
    for i in range(8):
        random_int = random.randint(0, 9)
        NUMBER += str(random_int)
        
    subject = "Password Reset"

    message = "Hello "
    message += User.objects.get(username = RESET_PASSWORD_USERNAME).get_full_name()
    message += "\n\nWe have recieved a request to reset your password \nHere is the code to so\n"
    message += NUMBER
    message += "\n\nThank you for using OnSchedule"

    email_from = settings.EMAIL_HOST_USER

    recipient = [User.objects.get(username = RESET_PASSWORD_USERNAME).email]

    send_mail(subject, message, email_from, recipient)

    return render(request, 'password_reset.html')

    
# Asks the user to put in the new password twice and moves on if it they were the same
def password_change_page(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        
        if password != confirm_password:
            messages.info(request, "Not the Same Password, Try Again")
            return redirect('/users/password_change')
        
        user = User.objects.get(username = RESET_PASSWORD_USERNAME)

        user.set_password(password)
        user.save()
        user.profile.save()
        return redirect ('/users/password_confirm')
        
    return render(request, 'password_change.html')

# Shows a screen that shows that the password reset was sucessful
def password_confirm_page(request):
    return render(request, 'password_confirm.html')

# Shows off the user's account information and allows the user to logout 
def account_information_page(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/users/login')
    
    if not request.user.is_authenticated:
        return render(request, 'account_information.html')
    
    username = request.user.username
    name = request.user.get_full_name()
    email = request.user.email


    #Mini Calendar
    #Get current date
    now = datetime.datetime.now()
    first_day_of_month = now.replace(day=1)
    weekday_name = first_day_of_month.strftime('%A')
    current_month_value = int(now.strftime('%m'))
    current_day_value = int(now.strftime('%d'))
    current_year_value = int(now.strftime('%Y'))
    current_month_days = calendar.monthrange(current_year_value, current_month_value)[1]
    month_days = list(range(1, current_month_days + 1))
    start_date = datetime.date(current_year_value, current_month_value, current_day_value)
    prev_month = getPreviousMonth(start_date)
    prev_date = calendar.monthrange(prev_month.year, prev_month.month)[1]
    prev_month_value = prev_month.strftime('%m')
    next_month = getNextMonth(start_date, current_month_days)
    next_month_value = next_month.strftime('%m')
    offset = getOffset(weekday_name)
    last_day = start_date.replace(day=current_month_days)
    offset_nums = list(range( prev_date - int(offset) + 1, prev_date + 1))
    next_offset = getNextOffsetDate(last_day.strftime('%A'))
    next_offset_nums = list(range(1, next_offset + 1 ))
    #end of mini calendar

    current_user = request.user 
    current_user_events = current_user.profile.created_events.all()
    attending_events = current_user.profile.events.all()
    month_date = current_month_value
    year_date = current_year_value
    month_events = current_user_events.filter(start_time__month=month_date, start_time__year=year_date)
    month_attending_events = attending_events.filter(start_time__month=month_date, start_time__year=year_date)
    month_events = (month_events | month_attending_events).distinct()
    next_month_events = current_user_events.filter(start_time__month=next_month_value, start_time__year=year_date)
    next_month_attending_events = attending_events.filter(start_time__month=next_month_value, start_time__year=year_date)
    next_month_events = (next_month_events | next_month_attending_events).distinct()
    prev_month_events = current_user_events.filter(start_time__month=prev_month_value, start_time__year=year_date)
    prev_month_attending_events = attending_events.filter(start_time__month=prev_month_value, start_time__year=year_date)
    prev_month_events = (prev_month_events | prev_month_attending_events).distinct()


    my_todo_events = month_events.filter(start_time__day=current_day_value)
    todo_events = my_todo_events[:5]
    user = request.user
    user_profile = request.user.profile
    context ={
        'username' : username, 
        'name' : name, 
        'email' : email,
        "current_user" : user,
        'friends' : user_profile.friendList.all,
        
        "todo_events" : todo_events,
        "offset_numbers" : offset_nums,
        "month_days_list" : month_days,
        "day_offset" : offset,
        "month_events" : month_events,
        "next_month_events" : next_month_events,
        "prev_month_events" :prev_month_events,
        "next_offset" : next_offset,
        "next_offset_nums" : next_offset_nums,
        "current_days" : current_month_days,
    }
    return render(request, 'account_information.html', context)

# Sets up the friend list to show off each of the user's friend and allowed the user to submit a username of another user to make them into a friend
def friend_list_page(request):
    global CURRENT_USER
    if request.method == 'POST':
        friend_username = request.POST.get('username')

        if friend_username == request.user.username:
            messages.error(request, 'You can not have yourself as a friend')
            return redirect('/users/friend_list')

        if not User.objects.filter(username = friend_username).exists():
            messages.error(request, 'User does not exist')
            return redirect('/users/friend_list')
        
        if request.user.profile.friendList.filter(Amigo__username=friend_username).exists():
            if request.user.profile.friendList.filter(Amigo__username=friend_username).first().viewable:
                messages.error(request, 'You are waiting for a response to your friend request to this person')
                return redirect('/users/friend_list')

app/users/templates/account_information.html
{% extends "calendar/base.html" %}

{% block title %}
My Calendar
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/monthview.css' %}">
<link rel="stylesheet" href="{% static 'accountinfo.css' %}">
{% endblock %}

{% block content %}

{% load mathfilters %}

<div class="account-container">


    <div class="account-info-container">
        <div class="basic-info-container">
        <div class="basic-info">
            <div class="info-section">
                Username: {{ current_user.username }}
            </div>
            <div class="info-section">
                Name: {{ current_user.first_name }} {{ current_user.last_name }}
            </div>
            <div class="info-section">
                Email: {{ current_user.email }}
            </div>
        </div>
        </div>
        <div class="friend-list-container">
            <div class="friend-header">
                Friend List
            </div>
            <div>
                {% block friendlist %}
                {% endblock %}
            </div>
        </div>
        
    </div>

    <div class="log-out-here">
        <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">

            {% csrf_token %}
    
            <p><a href="/cal/month"> Return to your Calendar </a></p>
    
            {% if name %}
            <div> 
                Log out of your account?
            </div>
            <button type="submit" class="logging-out"> 
                Log Out 
            </button>
    
            {% else %}
    
            <h1> User is not logged in</h1>
    
            {% endif %}
        </form>
    </div>
</div>


{% endblock %}

app/users/templates/base.html
<!doctype html>
<html lang="en-US">
  {% load static %}
  {% load mathfilters %}

  {% load calendar_filters %}
  
  <head>
    <meta charset="utf-8" />
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- Allow templates to inject their own types -->
    {% block head %}
    {% endblock %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">


  </head>

  <body>
      <div class="main-container">

        <div class="body-container">
          <div class="body-title">
            onSchedule
          </div>
    <!-- Login functionality gets placed here, but block code is found in another html file -->  
          {% block content %}
          {% endblock %}
        </div>
<!-- Decoration -->
        <div class="background-container rect-grid">
          <div class="rect-container shade-12">
          </div>

          <div class="rect-container shade-25">
          </div>

          <div class="rect-container shade-50">
          </div>

          <div class="rect-container shade-75">
          </div>
        </div>


      </div>
  </body>
</html>

app/users/templates/friend_list.html
{% extends "account_information.html" %}

{% block title %}
Register
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'calendar/monthview.css' %}">
<link rel="stylesheet" href="{% static 'accountinfo.css' %}">
<link rel="stylesheet" href="{% static 'friendlist.css' %}">
{% endblock %}

{% block friendlist %}

{% load mathfilters %}

<div class="big-container">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">

        {% csrf_token %}
        <!-- Messages that change based on User interaction -->
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>

        <div class="border-friends">
        <!-- A Loop that goes through each of the user's friends -->
        {% for friend in friends %}
        <div class="friend-box">
            <!-- States the users name -->
            <div class="friend-name">
                {{friend.Amigo.first_name}} {{friend.Amigo.last_name}}
            </div>
            <div class="status">
                <!-- Checks if the user has sent the request and the request has not been accepted or rejected -->
                {% if friend.viewable %}
                    <!-- If user is the receiving user, checks if the request is pending -->
                    {% if friend.requestPending %}
                        <div>
                            Incoming Requests
                        </div>
                        <!-- Button for the user to Accept the friend request -->
                        <a href="{% url 'users:accept_friend' friend.Amigo.username %}">Accept Friend Request</a>
                        <!-- Button for the user to Reject the friend request -->
                        <a href="{% url 'users:reject_friend' friend.Amigo.username %}">Reject Friend Request</a>
                    {% else %}
                        <!-- Button for the user to Enter the friend's calendar -->
                        <a href="{% url 'users:update_friend' friend.Amigo.username %}">
                            <div>
                                View Calendar
                            </div>
                        </a>
                    {% endif %}
                {% else %}
                    <div>
                        You are currently waiting for a response to your friend request to this user
                    </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        </div>

        <!-- Form which allows the user to insert username and send a friend request to them -->
        <div class="add-friends-box">
            <div class="bold-box">
                Want Friends?
            </div>
            <div class="basic-box">
                Put in their Username here
            </div>
            <label for="username" class="add-friends-box">
                
            </label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>
        </div>

        
    </form>
</div>

{% endblock %}

app/users/templates/home.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'home.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}
<!-- This html file is not in use -->

<div class="content-container-main">

  <div class="header">
    The Only Calendar You Will Ever Need

  </div>
  <div class="links-container">

    <div class="register-box">
      <div class="body">
        Get Started Now!
      </div>
      {% url 'users:register_page' as register %}
      <a href ="{{ register }}">
        <button class = "button-sign">
          Register
        </button>
      </a>
    </div>

    <div class="login-box">
      <div class="body">
        Continue Planning
      </div>
      {% url 'users:login_page' as login %}
      <a href ="{{ login }}">
        <button class="button-sign">
          Login
        </button>
      </a>
    </div>

  </div>
</div>

{% endblock %}

app/users/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'login.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}

<div class="login-container">
  <div class="title-container">
    Login
  </div>
  <div class="form-container">
    <form class="form-css" method="post" enctype="multipart/form-data">
    
      {% csrf_token %}
      
      <div class="" role="alert">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
      </div>
  <!-- Enter login credentials -->
      <div class="information-container">

        <div class="information-box">
          <label for="username">
              Username:
          </label>
          <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>
  
      </div>
  
      <div class="information-box">
          <label for="password">
              Password:
          </label>
          <input type="text" class="form-control" name="password" id="password" placeholder="Enter password" required>
          
      </div>
      </div>
       <!-- Sends you to another link if you click reset password or register now -->
      <div>Forgot your Password: <a href="{% url 'users:username_get_page' %}"> Reset Here </a></div>
  
      <div>Register Now: <a href= "{% url 'users:register_page' %}"> Register </a></div>
  
      <button type="submit" class="good-button"> Submit </button>
  </form>
  </div>
</div>

{% endblock %}

app/users/templates/password_change.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'register.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}
<!-- This is password reset html -->
<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Password Reset Confirm</h3>

        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
<!-- Input new password -->
        <div class="form-group">
            <label for="password">
                New Password:
            </label>
            <input type="text" class="form-control" name="password" id="password" placeholder="Enter password" required>
            
        </div>

        <div class="form-group">
            <label for="confirm_password">
                New Password Confirm:
            </label>
            <input type="text" class="form-control" name="confirm_password" id="confirm_password" placeholder="Reenter password" required>
            
        </div>

        <button type="submit" class="btn btn-primary"> Reset Password </button>
    </form>
</div>

{% endblock %}

app/users/templates/password_confirm.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'register.css' %}">

{% endblock %}

{% block content %}
<!-- Html for when user has successfully reset their password -->
{% load mathfilters %}
<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        
        {% csrf_token %}

        <h3> 
            Congratulations, you have reset your password
        </h3>
<!-- Link sends user back to login page -->
        <p>Please<a href="/login"> Login </a></p>
    </form>
</div>

{% endblock %}

app/users/templates/password_reset.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'register.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}
<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        <h1 style="text-align: center;">
            Reset Password
        </h1>
        
        {% csrf_token %}
<!-- Email is sent to user containing a code -->
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>

        <h3>
            You should recieve an email containing a 8 digit number, place that number here
        </h3>
<!-- User inputs code here -->        
        <div class="form-group">
            <label for="number">
                Number:
            </label>
            <input type="text" class="form-control" name="number" id="number" placeholder="Enter Number" required>

        </div>

        <button type="submit" class="btn btn-primary"> Submit </button>
    </form>
</div>

{% endblock %}

app/users/templates/register.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'register.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}
<!-- User inputs information to create an account in this file -->
<div class="login-container">
  <div class="title-container">
    Register
  </div>
  <div class="form-container">
    <form class="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="" role="alert">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
      </div>
  
      <div class="form-group">
          <label for="firstName">
              First Name:
          </label>
          <input type="text" class="form-control" id="firstName" placeholder="Enter First Name" name="first_name" required>
  
      </div>
  
      <div class="form-group">
          <label for="lastName">
              Last Name:
          </label>
          <input type="text" class="form-control" id="lastName" placeholder="Enter Last Name" name="last_name" required>
  
      </div>
  
      <div class="form-group">
          <label for="email">
              Email:
          </label>
          <input type="text" class="form-control" id="email" placeholder="Enter Email" name="email" required>
  
      </div>
  
      <div class="form-group">
          <label for="username">
              Username:
          </label>
          <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>
  
      </div>
  
      <div class="form-group">
          <label for="password">
              Password:
          </label>
          <input type="text" class="form-control" name="password" id="password" placeholder="Enter password" required>
          
      </div>
  
      <button type="submit" class="good-button"> Submit </button>
  </form>
  </div>

</div>

{% endblock %}

app/users/templates/username_get.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% load static %}

{% block head %}

<link rel="stylesheet" href="{% static 'register.css' %}">

{% endblock %}

{% block content %}

{% load mathfilters %}
<div class="container mt-5">
    <form class="col-6 mx-auto card p-3 shadow-lg" method="post" enctype="multipart/form-data">
        <h1 style="text-align: center;">
            Reset Password
        </h1>
        
        {% csrf_token %}

        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
  <!-- Identifies user before redirecting to resetting password -->       
        <div class="form-group">
            <label for="username">
                Username:
            </label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username" required>

        </div>

        <button type="submit" class="btn btn-primary"> Submit </button>
    </form>
</div>

{% endblock %}